// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPzYjSyl4o155SDOG79MArPP2H20trHA',
    appId: '1:519372495804:web:efd87f99a59cb0c565a9b9',
    messagingSenderId: '519372495804',
    projectId: 'yandex-school-todo-app',
    authDomain: 'yandex-school-todo-app.firebaseapp.com',
    storageBucket: 'yandex-school-todo-app.appspot.com',
    measurementId: 'G-1FWBM020GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0_OzJGh0q5UJZXW6YoVdzz7hCt0XPIAY',
    appId: '1:519372495804:android:1672ff996e47351665a9b9',
    messagingSenderId: '519372495804',
    projectId: 'yandex-school-todo-app',
    storageBucket: 'yandex-school-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYd61eL8TX7CnZY8Zu-0JMVIIG6ij_hxg',
    appId: '1:519372495804:ios:554b0d1175d868da65a9b9',
    messagingSenderId: '519372495804',
    projectId: 'yandex-school-todo-app',
    storageBucket: 'yandex-school-todo-app.appspot.com',
    iosClientId: '519372495804-21rdg9qdpbenaa81hhprirvgifnaij23.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
